export const environment = {
  appVersion: "3.2.3",
  production: true,
  cookie_domain: "oneplay.in",
  domain: "https://www.oneplay.in",
  client_api: "https://client-apis.oneplay.in/services/v2",
  render_mix_api: "https://rendermix.oneplay.in/v1",
  socket_endpoint: "https://chatservices.oneplay.in",
  game_assets: "https://cdn.edge-net.co/game_assets/",
  partner_id: "28cceed5-8ab9-11ed-bde5-0ab3c1edb81a",
  partner_name: 'onePlay',
  stripe_key:
    "pk_live_51MqHiCSIFX9lGIVVjAZU0jnZTHfvUbhLb8hGS9yipxYZroAss0GJRSbKsCXIpQynjsuAhwYZj4tHgFkYp2ETCxcD00CGHkBRf8",
  billdesk_key: "ONEPLAY2",
  billdesk_sdk_prefix: "https://pay.billdesk.com/jssdk/v1/dist",
  firebase: {
    apiKey: "AIzaSyC5milGrnk5xUZyniQfvEVjd3CIX72puBA",
    authDomain: "oneplay-ba044.firebaseapp.com",
    projectId: "oneplay-ba044",
    storageBucket: "oneplay-ba044.appspot.com",
    messagingSenderId: "744840875406",
    appId: "1:744840875406:web:056e488d551ade3e9ba8df",
    measurementId: "G-X80K2YEKBS",
  },
  countly: {
    key: "292851cc7abdfc6770504910155cd0de1307024e",
    url: "https://analytics-api.oneplay.in/",
  },
  webrtc_prefix: "https://www.oneplay.in/webplay",
};
